In [1]:
import mlflow
import polars as pl
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score
from torch.utils.data import DataLoader, Dataset
from torchinfo import summary
from tqdm.notebook import tqdm
from transformers import AutoModel, AutoTokenizer
from transformers.models.bert.modeling_bert import BertModel
from mlflow.models import infer_signature

# Types
from transformers.models.bert.tokenization_bert_fast import BertTokenizerFast

import matplotlib.pyplot as plt
from src.config import MPL_STYLE_DIR, PROCESSED_DATA_DIR
from src.db import PBWarehouse
from src.models import Tweet

mlflow.set_tracking_uri("http://192.168.100.203:5000")
mlflow.set_experiment("[CAPSTONE-2] hatebert-finetuning")

warehouse = PBWarehouse()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

2025-07-12 09:18:35.058 | INFO     | src.config:<module>:26 - Loaded environment variables from /home/iragca/Documents/github/capstone-project-2/.env
2025-07-12 09:18:35.058 | INFO     | src.config:<module>:60 - PROJECT_ROOT: /home/iragca/Documents/github/capstone-project-2
2025-07-12 09:18:35.059 | INFO     | src.config:<module>:61 - DATA_DIR: /home/iragca/Documents/github/capstone-project-2/data
2025/07/12 09:18:35 INFO mlflow.tracking.fluent: Experiment with name '[CAPSTONE-2] hatebert-finetuning' does not exist. Creating a new experiment.

device(type='cuda')

In [2]:
data = warehouse.client.collection("tweets_v2").get_full_list(
    query_params={
        "filter": (
            "has_blm_hashtag = true || "
            "is_reply_to_blm = true && "
            "creation_date >= '2020-03-26' "
            "&& creation_date <= '2020-07-24' "
            "&& language = 'en'",
        )
    }
)
tweets: list[Tweet] = [Tweet(**r.__dict__) for r in data]

In [3]:
df = pl.DataFrame(
    [t.model_dump() for t in tweets],
    schema={
        "tweet_id": pl.Utf8,
        "text": pl.Utf8,
        "status_link": pl.Utf8,
        "user_id": pl.Utf8,
        "is_extremist": pl.Boolean,
        "is_annotated": pl.Boolean,
        "in_reply_to_status_link": pl.Utf8,
        "in_reply_to_status_id": pl.Utf8,
        "bookmark_count": pl.Int64,
        "views": pl.Int64,
        "retweet_count": pl.Int64,
        "favorite_count": pl.Int64,
        "reply_count": pl.Int64,
        "quote_count": pl.Int64,
        "conversation_id": pl.Utf8,
        "retweet_tweet_id": pl.Utf8,
        "quoted_status_id": pl.Utf8,
        "community_note": pl.Utf8,
        "language": pl.Utf8,
        "source": pl.Utf8,
        "creation_date": pl.Utf8,
        "has_blm_hashtag": pl.Boolean,
        "fetched_replies": pl.Boolean,
        "is_reply_to_blm": pl.Boolean,
    },
).with_columns(
    pl.col("creation_date").str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S%.3fZ")
)
df

shape: (42_201, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ tweet_id  ┆ text      ┆ status_li ┆ user_id   ┆ … ┆ creation_ ┆ has_blm_h ┆ fetched_r ┆ is_reply │
│ ---       ┆ ---       ┆ nk        ┆ ---       ┆   ┆ date      ┆ ashtag    ┆ eplies    ┆ _to_blm  │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ datetime[ ┆ bool      ┆ bool      ┆ bool     │
│           ┆           ┆           ┆           ┆   ┆ ms]       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 126991675 ┆ @TRCdocum ┆ https://x ┆ 126484605 ┆ … ┆ 2020-06-0 ┆ false     ┆ false     ┆ true     │
│ 671968563 ┆ entary    ┆ .com/hype ┆ 790680678 ┆   ┆ 8         ┆           ┆           ┆          │
│ 2         ┆ @Blklives ┆ rsoses/st ┆ 6         ┆   ┆ 08:58:43  ┆           ┆           ┆          │
│           ┆ matte…    ┆ atu…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 127797691 ┆ @terrycre ┆ https://x ┆ 23719684  ┆ … ┆ 2020-06-3 ┆ true      ┆ true      ┆ true     │
│ 374350336 ┆ ws @jonat ┆ .com/TheJ ┆           ┆   ┆ 0         ┆           ┆           ┆          │
│ 5         ┆ hanwsabin ┆ aredMonro ┆           ┆   ┆ 14:46:54  ┆           ┆           ┆          │
│           ┆ Th…       ┆ e/s…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128571495 ┆ Join      ┆ https://x ┆ 108197333 ┆ … ┆ 2020-07-2 ┆ true      ┆ false     ┆ false    │
│ 089644339 ┆ Bernie    ┆ .com/Sunr ┆ 601030963 ┆   ┆ 1         ┆           ┆           ┆          │
│ 5         ┆ and       ┆ iseMvmtHT ┆ 2         ┆   ┆ 23:15:06  ┆           ┆           ┆          │
│           ┆ Sunrise   ┆ X/s…      ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ leader…   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128420953 ┆ @prageru  ┆ https://x ┆ 190751291 ┆ … ┆ 2020-07-1 ┆ false     ┆ false     ┆ true     │
│ 556181811 ┆ It's not  ┆ .com/chek ┆           ┆   ┆ 7         ┆           ┆           ┆          │
│ 2         ┆ the       ┆ mate111/s ┆           ┆   ┆ 19:33:07  ┆           ┆           ┆          │
│           ┆ women's … ┆ tat…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 157554045 ┆ Imagine   ┆ https://x ┆ 153572723 ┆ … ┆ 2022-09-2 ┆ true      ┆ true      ┆ false    │
│ 148601139 ┆ being     ┆ .com/Unio ┆ 515560755 ┆   ┆ 9         ┆           ┆           ┆          │
│ 2         ┆ homeless, ┆ nBaddieMa ┆ 3         ┆   ┆ 17:38:10  ┆           ┆           ┆          │
│           ┆ then t…   ┆ tt/…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 124334830 ┆ You       ┆ https://x ┆ 108258892 ┆ … ┆ 2020-03-2 ┆ true      ┆ false     ┆ false    │
│ 190014054 ┆ shouldn’t ┆ .com/grea ┆ 041472000 ┆   ┆ 7         ┆           ┆           ┆          │
│ 4         ┆ get down  ┆ t_african ┆ 0         ┆   ┆ 01:25:10  ┆           ┆           ┆          │
│           ┆ to the …  ┆ /st…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 126954903 ┆ @AmberLot ┆ https://x ┆ 553976157 ┆ … ┆ 2020-06-0 ┆ false     ┆ true      ┆ true     │
│ 305329049 ┆ us21 @Dav ┆ .com/Acti ┆           ┆   ┆ 7         ┆           ┆           ┆          │
│ 9         ┆ id7658378 ┆ velyWoke1 ┆           ┆   ┆ 08:37:31  ┆           ┆           ┆          │
│           ┆ 3 D…      ┆ /st…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 124202853 ┆ Overseas  ┆ https://x ┆ 860520162 ┆ … ┆ 2020-03-2 ┆ true      ┆ false     ┆ false    │
│ 954682880 ┆ #American ┆ .com/Dems ┆ 939850752 ┆   ┆ 3         ┆           ┆           ┆          │
│ 1         ┆ #Voters   ┆ AbroadDE/ ┆           ┆   ┆ 10:00:54  ┆           ┆           ┆          │
│           ┆ Req…      ┆ sta…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 123858692 ┆ Book -    ┆ https://x ┆ 750465507 ┆ … ┆ 2020-03-1 ┆ true      ┆ false     ┆ false    │
│ 799087001 ┆ Black     ┆ .com/book ┆ 527057408 ┆   ┆ 3         ┆           ┆           ┆          │
│ 9         ┆ Public    ┆ _souk/sta ┆           ┆   ┆ 22:05:10  ┆           ┆           ┆          │
│           ┆ History   ┆ tus…      ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ in…       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 127557661 ┆ We dont   ┆ https://x ┆ 314652960 ┆ … ┆ 2020-06-2 ┆ true      ┆ false     ┆ false    │
│ 614038630 ┆ have to   ┆ .com/IamA ┆ 0         ┆   ┆ 3         ┆           ┆           ┆          │
│ 4         ┆ wait for  ┆ nuNaik/st ┆           ┆   ┆ 23:48:59  ┆           ┆           ┆          │
│           ┆           ┆ atu…      ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ pol…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_name = "Hate-speech-CNERG/bert-base-uncased-hatexplain"  # HATEBERT on Hugging Face

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

In [9]:
inputs = tokenizer("I hate black people", return_tensors="pt")
outputs = model(**inputs)

logits = outputs.logits

probs = torch.nn.functional.softmax(logits, dim=-1)
predicted_class = torch.argmax(probs, dim=-1)

print(f"Logits: {logits}")
print(f"Probabilities: {probs}")
print(f"Predicted class: {predicted_class.item()}")

Logits: tensor([[-1.0975,  0.3231, -0.1099]], grad_fn=<AddmmBackward0>)
Probabilities: tensor([[0.1278, 0.5291, 0.3431]], grad_fn=<SoftmaxBackward0>)
Predicted class: 1

In [10]:
test_df = df.select(
    [
        pl.col("text"),
    ]
).with_columns(pl.lit(None).alias("is_hateful").cast(pl.Int8))
test_df

shape: (42_201, 2)
┌─────────────────────────────────┬────────────┐
│ text                            ┆ is_hateful │
│ ---                             ┆ ---        │
│ str                             ┆ i8         │
╞═════════════════════════════════╪════════════╡
│ @TRCdocumentary @Blklivesmatte… ┆ null       │
│ @terrycrews @jonathanwsabin Th… ┆ null       │
│ Join Bernie and Sunrise leader… ┆ null       │
│ @prageru It's not the women's … ┆ null       │
│ Imagine being homeless, then t… ┆ null       │
│ …                               ┆ …          │
│ You shouldn’t get down to the … ┆ null       │
│ @AmberLotus21 @David76583783 D… ┆ null       │
│ Overseas #American #Voters Req… ┆ null       │
│ Book - Black Public History in… ┆ null       │
│ We dont have to wait for        ┆ null       │
│                                 ┆            │
│ pol…                            ┆            │
└─────────────────────────────────┴────────────┘

In [11]:
def classify_text(text: str) -> int:
    inputs = tokenizer(text, return_tensors="pt")
    outputs = model(**inputs)
    logits = outputs.logits
    probs = torch.nn.functional.softmax(logits, dim=-1)
    predicted_class = torch.argmax(probs, dim=-1)
    return predicted_class.item()

In [12]:
classify_text("I hate you")

1

In [13]:
test_df = df.with_columns(
    pl.col("text").map_elements(lambda x: classify_text(x), return_dtype=pl.Int8).alias("is_hateful")
)

In [14]:
test_df.write_csv(PROCESSED_DATA_DIR / "hatebert-test.csv")
# test_df = pl.read_csv(PROCESSED_DATA_DIR / "hatebert-test.csv")

In [15]:
test_df

shape: (42_201, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ tweet_id  ┆ text      ┆ status_li ┆ user_id   ┆ … ┆ has_blm_h ┆ fetched_r ┆ is_reply_ ┆ is_hatef │
│ ---       ┆ ---       ┆ nk        ┆ ---       ┆   ┆ ashtag    ┆ eplies    ┆ to_blm    ┆ ul       │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ bool      ┆ bool      ┆ bool      ┆ i8       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 126991675 ┆ @TRCdocum ┆ https://x ┆ 126484605 ┆ … ┆ false     ┆ false     ┆ true      ┆ 1        │
│ 671968563 ┆ entary    ┆ .com/hype ┆ 790680678 ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ @Blklives ┆ rsoses/st ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│           ┆ matte…    ┆ atu…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 127797691 ┆ @terrycre ┆ https://x ┆ 23719684  ┆ … ┆ true      ┆ true      ┆ true      ┆ 1        │
│ 374350336 ┆ ws @jonat ┆ .com/TheJ ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ hanwsabin ┆ aredMonro ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Th…       ┆ e/s…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128571495 ┆ Join      ┆ https://x ┆ 108197333 ┆ … ┆ true      ┆ false     ┆ false     ┆ 1        │
│ 089644339 ┆ Bernie    ┆ .com/Sunr ┆ 601030963 ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ and       ┆ iseMvmtHT ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│           ┆ Sunrise   ┆ X/s…      ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ leader…   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128420953 ┆ @prageru  ┆ https://x ┆ 190751291 ┆ … ┆ false     ┆ false     ┆ true      ┆ 1        │
│ 556181811 ┆ It's not  ┆ .com/chek ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ the       ┆ mate111/s ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ women's … ┆ tat…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 157554045 ┆ Imagine   ┆ https://x ┆ 153572723 ┆ … ┆ true      ┆ true      ┆ false     ┆ 1        │
│ 148601139 ┆ being     ┆ .com/Unio ┆ 515560755 ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ homeless, ┆ nBaddieMa ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│           ┆ then t…   ┆ tt/…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 124334830 ┆ You       ┆ https://x ┆ 108258892 ┆ … ┆ true      ┆ false     ┆ false     ┆ 1        │
│ 190014054 ┆ shouldn’t ┆ .com/grea ┆ 041472000 ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ get down  ┆ t_african ┆ 0         ┆   ┆           ┆           ┆           ┆          │
│           ┆ to the …  ┆ /st…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 126954903 ┆ @AmberLot ┆ https://x ┆ 553976157 ┆ … ┆ false     ┆ true      ┆ true      ┆ 1        │
│ 305329049 ┆ us21 @Dav ┆ .com/Acti ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9         ┆ id7658378 ┆ velyWoke1 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 3 D…      ┆ /st…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 124202853 ┆ Overseas  ┆ https://x ┆ 860520162 ┆ … ┆ true      ┆ false     ┆ false     ┆ 1        │
│ 954682880 ┆ #American ┆ .com/Dems ┆ 939850752 ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ #Voters   ┆ AbroadDE/ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Req…      ┆ sta…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 123858692 ┆ Book -    ┆ https://x ┆ 750465507 ┆ … ┆ true      ┆ false     ┆ false     ┆ 1        │
│ 799087001 ┆ Black     ┆ .com/book ┆ 527057408 ┆   ┆           ┆           ┆           ┆          │
│ 9         ┆ Public    ┆ _souk/sta ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ History   ┆ tus…      ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ in…       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 127557661 ┆ We dont   ┆ https://x ┆ 314652960 ┆ … ┆ true      ┆ false     ┆ false     ┆ 2        │
│ 614038630 ┆ have to   ┆ .com/IamA ┆ 0         ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ wait for  ┆ nuNaik/st ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ atu…      ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ pol…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [16]:
test_df.filter(pl.col("is_hateful") == 2).select(
    [pl.col("text"), pl.col("is_hateful")],
).to_pandas()

                                                  text  is_hateful
0    @ukblm This sounds like a fairytale anyway.\n\...           2
1    Nice! Black Lives Matter doesn't even bother t...           2
2    @Trace___65roses So a career criminal is the n...           2
3                             @BLMSeattleKC Eat a dick           2
4    I have to say: @UncleTomDoc Part II is AMAZING...           2
..                                                 ...         ...
867  White gays need to start making good on the #B...           2
868  @johncardillo @gatewaypundit #BlackLivesMatter...           2
869  @ScotsmanGrumpy The gaming community will neve...           2
870  @MurielBowser The racist trying to sue you in ...           2
871  We dont have to wait for \n\npolitical letharg...           2

[872 rows x 2 columns]

In [17]:
test_df.filter(pl.col("is_hateful") == 1).select(
    [pl.col("text"), pl.col("is_hateful")],
).to_pandas()

                                                    text  is_hateful
0             @TRCdocumentary @Blklivesmatter only shits           1
1      @terrycrews @jonathanwsabin The very fact that...           1
2      Join Bernie and Sunrise leaders tomorrow at 7:...           1
3      @prageru It's not the women's body. It is a se...           1
4      Imagine being homeless, then the proletarian r...           1
...                                                  ...         ...
41246  LOUnited March today with @OleMissFB and other...           1
41247  You shouldn’t get down to the mud just to prov...           1
41248  @AmberLotus21 @David76583783 Did the police of...           1
41249  Overseas #American #Voters Request your ballot...           1
41250  Book - Black Public History in Chicago: #Civil...           1

[41251 rows x 2 columns]

In [18]:
test_df.filter(pl.col("is_hateful") == 0).select(
    [pl.col("text"), pl.col("is_hateful")],
).to_pandas()

                                                 text  is_hateful
0   @lausanhk @b9AcE @rhaphiikii Imperialist tools...           0
1   I gained the Covid 15 and still working multip...           0
2   @7NewsBrisbane burning our flag. no good cunt'...           0
3   @CameronRidle DNR filed charges with Prosecuto...           0
4   @CopWithAttitude I have a bad feeling they wou...           0
..                                                ...         ...
73  Goldie Star chokes on Big Black Cock 🙋🏼‍♀️👄🍆♠️...           0
74  Four years on from the @hackneygazette's headl...           0
75  If your defeat makes you horny, you are owned....           0
76  @realNick_777 @malibujonfanti @RudyGiuliani On...           0
77  Every day I’m just amazed by how much absolute...           0

[78 rows x 2 columns]

In [6]:
def has_hateful_words(text: str) -> bool:

    terms = [
        "bnwo",
        "bbc",
        "blacksupremacy",
        "queenofspades",
        "blacked",
        "qos"
    ]

    return any(term in text.lower() for term in terms)

hate_df = test_df.with_columns(
    pl.col("text").map_elements(lambda x: has_hateful_words(x), return_dtype=pl.Boolean).alias("has_hateful_words")
)

In [ ]:
hate_df["has_hateful_words"]

shape: (2, 2)
┌───────────────────┬───────┐
│ has_hateful_words ┆ count │
│ ---               ┆ ---   │
│ bool              ┆ u32   │
╞═══════════════════╪═══════╡
│ true              ┆ 590   │
│ false             ┆ 41845 │
└───────────────────┴───────┘

In [22]:
hate_df = test_df.with_columns(
    pl.col("creation_date").str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S%.3fZ")  
    )

InvalidOperationError: conversion from `str` to `datetime[ms]` failed in column 'creation_date' for 226 out of 226 values: ["2020-06-03T14:19:15.000", "2020-06-12T15:06:50.000", … "2020-06-19T19:08:21.000"]

You might want to try:
- setting `strict=False` to set values that cannot be converted to `null`
- using `str.strptime`, `str.to_date`, or `str.to_datetime` and providing a format string

In [21]:
hate_df

shape: (42_435, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ tweet_id  ┆ text      ┆ status_li ┆ user_id   ┆ … ┆ has_blm_h ┆ fetched_r ┆ is_reply_ ┆ is_hatef │
│ ---       ┆ ---       ┆ nk        ┆ ---       ┆   ┆ ashtag    ┆ eplies    ┆ to_blm    ┆ ul       │
│ i64       ┆ str       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ bool      ┆ bool      ┆ bool      ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 128644741 ┆ Heyhey if ┆ https://x ┆ 347913343 ┆ … ┆ true      ┆ true      ┆ false     ┆ 1        │
│ 508031283 ┆ you are   ┆ .com/Chuc ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ someone/k ┆ kMockler/ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ now…      ┆ sta…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128644093 ┆ Thank you ┆ https://x ┆ 833871911 ┆ … ┆ true      ┆ true      ┆ false     ┆ 1        │
│ 810616320 ┆ @VoteAdam ┆ .com/Adam ┆ 272722433 ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ Medrano   ┆ Bazaldua/ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ for…      ┆ sta…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128645049 ┆ I have    ┆ https://x ┆ 773036078 ┆ … ┆ false     ┆ true      ┆ true      ┆ 1        │
│ 632928563 ┆ ten-ish   ┆ .com/Lily ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ years of  ┆ ShumarKra ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ experi…   ┆ y/s…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128644976 ┆ Opening   ┆ https://x ┆ 114821296 ┆ … ┆ true      ┆ true      ┆ false     ┆ 1        │
│ 450729165 ┆ day is    ┆ .com/Harr ┆ 733220454 ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆ underway  ┆ isWarRoom ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆ for @m…   ┆ /st…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128643907 ┆ People    ┆ https://x ┆ 108571906 ┆ … ┆ true      ┆ true      ┆ false     ┆ 1        │
│ 623365017 ┆ are       ┆ .com/Soli ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7         ┆ either    ┆ Philander ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ being Dof ┆ /st…      ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ an…       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 127594732 ┆ @johncard ┆ https://x ┆ 179785566 ┆ … ┆ false     ┆ false     ┆ true      ┆ 1        │
│ 598324428 ┆ illo This ┆ .com/Main ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8         ┆ is such   ┆ StreetMus ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ BS.…      ┆ e/s…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 126905699 ┆ @rebeinst ┆ https://x ┆ 249639906 ┆ … ┆ false     ┆ false     ┆ true      ┆ 1        │
│ 017893888 ┆ ein ...   ┆ .com/alan ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ 0         ┆ the only  ┆ ekennedyl ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ good…     ┆ aw/…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 127300029 ┆ @tomselli ┆ https://x ┆ 728434941 ┆ … ┆ false     ┆ false     ┆ true      ┆ 1        │
│ 272066867 ┆ ott       ┆ .com/MSMC ┆ 843804161 ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ @dbongino ┆ ali/statu ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ @thread…  ┆ s/1…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 127396923 ┆ @HackneyA ┆ https://x ┆ 119204675 ┆ … ┆ false     ┆ false     ┆ true      ┆ 1        │
│ 301424332 ┆ bbott @so ┆ .com/Shea ┆ 906690252 ┆   ┆           ┆           ┆           ┆          │
│ 8         ┆ cialistca ┆ rerDan7/s ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│           ┆ m T…      ┆ tat…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 126954903 ┆ @AmberLot ┆ https://x ┆ 553976157 ┆ … ┆ false     ┆ false     ┆ true      ┆ 1        │
│ 305329049 ┆ us21 @Dav ┆ .com/Acti ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9         ┆ id7658378 ┆ velyWoke1 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 3 D…      ┆ /st…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
sorted_df = hate_df.filter(pl.col("has_hateful_words")).sort(pl.col("creation_date")).group_by_dynamic("creation_date", every="1m").agg(
    [
        pl.col("tweet_id").count().alias("total_tweets"),
    ])

ComputeError: null values in dynamic group_by not supported, fill nulls.